apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: react-v1
  name: react-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-v1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: react-v1
    spec:
      containers:
      - image: ts00328685/heloword-react-v1:1.MINOR_VERSION
        name: react-v1
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: react-v1
  name: react-v1-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: react-v1
status:
  loadBalancer: {}
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: react-v1-ingress-v1
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: react-v1-service
            port:
              number: 80
        path: /react/v1(/|$)(.*)
        pathType: Prefix